/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsBrain = Brain
export declare class Brain {
  /**
   * Create a new Brain instance from an options object.
   *
   * Options shape (all optional, with defaults matching JS Brain):
   *   contextLength: number (default 10)
   *   errorCorrectionMode: string (default 'conservative')
   *   errorCorrectionThreshold: number (default 0.5)
   *   mergeThreshold: number (default 0.5)
   *   patternForgetRate: number (default 0.01)
   *   regions: number (default 1)
   *   columns: number (default 1)
   *   debug: boolean (default false)
   */
  constructor(options?: object | undefined | null)
  /**
   * Register a channel spec. Accepts the same spec shape as JS Brain.
   *
   * spec: { name, emitsReward?, learnActionSequences?, dimensions: [...] }
   * Returns: { channelId: number, dimensionIds: {name: id, ...} }
   */
  registerChannelSpec(spec: object): object
  /**
   * Process a single frame. Accepts Maps matching JS Brain.processFrame.
   *
   * events: Map<channelId, Map<dimId, scalar>> — sensory inputs
   * actions: Map<channelId, Map<dimId, actionValue>> — forced actions (empty = infer)
   * rewards: Map<channelId, reward> — reward for previous frame's actions
   * Returns: { inferences: Map<channelId, [...]>, frame: { elapsed, voteDebug } }
   */
  processFrame(events: object, actions: object, rewards: object): object
  /**
   * Direct supervised learning: wire action connections from context neurons
   * and return inference result to test if learning took effect.
   */
  learn(actions: object, rewards: object): object
  /** Run inference on the current context without advancing the frame. */
  infer(): object
  /**
   * Get active neurons in context with their levels.
   * Returns an array of { neuronId, level, suppressed } objects.
   * suppressed=true means the neuron activated a higher-level pattern and
   * should not be counted as an independent voter.
   */
  getActiveNeurons(): object
  /**
   * Inspect one neuron: returns { neuronId, level, parentId | null,
   * context: [{ neuronId, distance, strength }, ...] }.
   * Context entries come from the parent neuron's routing-table entry
   * for this child pattern. Level-0 sensory neurons have parent_id=null
   * and empty context.
   */
  inspectNeuron(neuronId: number): object
  /**
   * Dump a neuron's outgoing connections.
   * Returns [{ distance, targetId, strength, reward }, ...].
   */
  dumpNeuronConnections(neuronId: number): object
  /**
   * List currently votable entries: same (neuronId, age) pairs that
   * infer() and learn() use to collect votes / wire connections.
   */
  getVotableEntries(): object
  /**
   * Implant: begin direct teaching mode for column-major training.
   * Caller must have already registered the event channel; pass the
   * channel id and dim id along with the number of training images.
   */
  startImplant(channelId: number, dimId: number, numImages: number): void
  /**
   * Implant: process one position across all images. `bits` is the
   * bucket id of each image's bit at this position, in the same order
   * `num_images` was given to startImplant. Brain handles per-image
   * state internally — caller just feeds bits position-by-position.
   */
  implantPosition(bits: Array<number>): void
  /** Implant: end implant mode. Returns { positionsProcessed, patternsCreated }. */
  finalizeImplant(): object
  /** Reset brain memory state for a clean episode start. */
  resetContext(): void
  /**
   * Initialize N parallel runtime contexts. Each context has its own
   * (memory, frame_number, rewards); the thalamus is shared. Pass the
   * target context id via setActiveContext before processFrame/learn/infer.
   */
  initContexts(n: number): void
  /**
   * Switch the active context. Subsequent processFrame/learn/infer/
   * resetContext calls operate on this context.
   */
  setActiveContext(ctxId: number): void
  /** Hard reset: clears ALL learned data. */
  resetBrain(): void
  /** Reset accuracy and reward stats for a new episode. */
  resetAccuracyStats(): void
  /**
   * Set processing mode flags.
   * eventProcessing: when false, freezes context (no aging, no new activations).
   * actionProcessing: when false, suppresses action inference and rewards.
   * learning: when false, skips pattern creation and connection learning (recognition only).
   */
  setProcessingMode(eventProcessing: boolean, actionProcessing: boolean, learning: boolean): void
  /** Look up a dimension ID by its registered name. */
  getDimensionIdByName(name: string): unknown
  /** Look up a neuron ID by its (dimId, bucketId) coordinate. */
  getNeuronIdByCoordinate(dimId: number, bucketId: number): unknown
  /** Save brain state to a labeled backup folder. */
  save(jobDir: string, label: string): void
  /** Load a backup by label. */
  load(jobDir: string, label: string): void
  /** Save brain context (active neurons, frame number, rewards) to a labeled folder. */
  saveContext(jobDir: string, label: string): void
  /** Load brain context from a labeled folder. */
  loadContext(jobDir: string, label: string): void
  /** Get the per-frame summary for the renderer. */
  getFrameSummary(): object
  /** Get episode summary with all diagnostic information. */
  getEpisodeSummary(): object
  /** Get start-of-frame diagnostic snapshot. Returns null when frame was empty. */
  getStartFrameInfo(): unknown
}
