/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsBrain = Brain
export declare class Brain {
  /**
   * Create a new Brain instance from an options object.
   *
   * Options shape (all optional, with defaults matching JS Brain):
   *   contextLength: number (default 10)
   *   groupThreshold: number (default 0.5) — the single grouping coefficient θ, shared by spatial and temporal.
   *     It SEEDS one adaptive per-unit threshold: recognition fires at similarity ≥ θ and correction at < θ
   *     until a unit has error history, after which both float together off its stats (see groupMode).
   *   groupMode: string (default 'neutral') — how the live grouping threshold adapts from error stats
   *     ('static' pins it at the θ seed; conservative/neutral/aggressive shift it by mean ± σ)
   *   patternForgetRate: number (default 0.01)
   *   regions: number (default 1)
   *   columns: number (default 1)
   *   consensus: string 'democratic' | 'nb' (default 'democratic')
   *   debug: boolean (default false)
   *
   * The retired per-phase `mergeThreshold` / `errorCorrectionThreshold` knobs and their `spatial*` / `temporal*`
   * variants collapsed into the single `groupThreshold` — `error = 1 − merge` is one Jaccard test read from
   * opposite sides, so there is one number, not six. Passing any retired key logs a one-time warning and is ignored.
   */
  constructor(options?: object | undefined | null)
  /**
   * Register a channel spec. Accepts the same spec shape as JS Brain.
   *
   * spec: { name, learnActionSequences?, dimensions: [...] }
   * Returns: { channelId: number, dimensionIds: {name: id, ...} }
   */
  registerChannelSpec(spec: object): object
  /**
   * Process a single frame. Accepts Maps matching JS Brain.processFrame.
   *
   * inputs: Map<channelId, Map<dimId, scalar>>
   * rewards: Map<channelId, reward>
   * Returns: { inferences: Map<channelId, [...]>, votes: Array<...>, frame: { elapsed, timings } }
   */
  processFrame(inputs: object, rewards: object): object
  /**
   * Get active neurons in context with their levels.
   * Returns an array of { neuronId, temporalLevel, suppressed } objects.
   * suppressed=true means the neuron activated a higher-level pattern and
   * should not be counted as an independent voter.
   */
  getActiveNeurons(): object
  /**
   * Inspect one neuron: returns { neuronId, temporalLevel, parentId | null,
   * context: [{ neuronId, distance, strength }, ...] }.
   * Context entries come from the parent neuron's routing-table entry
   * for this child pattern. Level-0 sensory neurons have parent_id=null
   * and empty context.
   */
  inspectNeuron(neuronId: number): object
  /**
   * Dump a neuron's outgoing connections.
   * Returns [{ distance, targetId, strength, reward }, ...].
   */
  getNeuronConnections(neuronId: number): object
  /**
   * Toggle per-vote resolution on processFrame's `votes` payload. Off by
   * default — per-vote resolution allocates strings and walks parent
   * chains, so training runs that don't consume votes pay nothing.
   */
  setEmitVotes(enabled: boolean): void
  /**
   * Master learning toggle.
   * When false, subsequent `processFrame` calls skip op-2 (decay/reap) and error-correction pattern neuron creation.
   * They also skip event→event connection strengthening, child-activation strengthening, and accuracy-stats tracking.
   * Sensory neuron creation (op-1) still runs because without it the frame cannot be processed at all.
   * Pattern activation and voting still run, so inferences remain populated.
   * Used by supervised harnesses (MNIST) for the held-out evaluation pass.
   */
  setLearning(learning: boolean): void
  /**
   * Supervised wiring step that sits on top of the last `processFrame` call.
   * `actions: Map<channelId, Map<dimId, Map<value, reward>>>` names every action target with its per-value reward.
   * Each `value` is quantized to the corresponding action neuron; reward is applied to that connection
   * via smoothed accumulation (strength += 1, reward = running mean). Callers typically supply every action value
   * on the dim — correct value with reward=1, others with reward=0 — so `conn.reward` converges to P(target|voter).
   * `distance` is the connection-table slot at which to wire and read back.
   * Wires every currently-active age-0 voter to every supplied action target at the given distance.
   * Then runs a post-wire inference sweep at age (distance - 1) and returns the resulting FrameResult.
   * Single-frame supervised harnesses (MNIST) pass distance=1 to match the existing temporal voting slot.
   */
  learn(actions: object, distance: number): object
  /** Reset brain memory state for a clean episode start. */
  resetContext(): void
  /** Hard reset: clears ALL learned data. */
  resetBrain(): void
  /** Reset accuracy and reward stats for a new episode. */
  resetAccuracyStats(): void
  /** Cumulative count of spatial corrections minted since brain start (or last hard reset). */
  getSpatialCorrectionCount(): number
  /** Number of correction neurons currently sitting above the base spatial level. */
  countActiveSpatialCorrections(): number
  /**
   * Per-level count of correction neurons. Returns array where index 0 is level 1, etc.
   * Length tells you the maximum spatial level reached.
   */
  spatialLevelCounts(): Array<number>
  /**
   * Dump active spatial corrections (level ≥ 1) with the footprint of each, for visualizing the
   * hierarchy. Reflects the most recently processed frame. Returns a JSON string:
   * `[{"id":N,"level":L,"ch":[channelIds...],"bk":[bucketIds...]}, ...]` where ch[i]/bk[i] is one
   * base pixel the correction covers. Parse with JSON.parse on the JS side.
   */
  dumpActiveSpatialCorrections(): string
  /**
   * Declare the base-level neighbor channel set for a registered channel — THE neighbor graph that
   * footprint adjacency uses in both waves (spatial and temporal). Names not in the registry are
   * silently ignored; an empty list shrinks the neighborhood to {itself}; channels with no call
   * retain the default all-pairs neighborhood. Call AFTER registering all channels — neighbor names
   * are resolved at this call. (Kept named `setSpatialNeighbors` for API stability.)
   */
  setSpatialNeighbors(name: string, neighborNames: Array<string>): void
  /** Look up a dimension ID by its registered name. */
  getDimensionIdByName(name: string): unknown
  /** Look up a neuron ID by its (dimId, bucketId) coordinate. */
  getNeuronIdByCoordinate(dimId: number, bucketId: number): unknown
  /** Save brain state to a labeled backup folder. */
  save(jobDir: string, label: string): void
  /** Load a backup by label. */
  load(jobDir: string, label: string): void
  /** Save brain context (active neurons, frame number, rewards) to a labeled folder. */
  saveContext(jobDir: string, label: string): void
  /** Load brain context from a labeled folder. */
  loadContext(jobDir: string, label: string): void
  /** Get the per-frame summary for the renderer. */
  getFrameSummary(): object
  /** Get episode summary with all diagnostic information. */
  getEpisodeSummary(): object
  /** Get start-of-frame diagnostic snapshot. Returns null when frame was empty. */
  getStartFrameInfo(): unknown
}
