/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsBrain = Brain
export declare class Brain {
  /**
   * Create a new Brain instance from an options object.
   *
   * Options shape (all optional, with defaults matching JS Brain):
   *   contextLength: number (default 10)
   *   errorCorrectionMode: string (default 'conservative')
   *   errorCorrectionThreshold: number (default 0.5)
   *   mergeThreshold: number (default 0.5)
   *   patternForgetRate: number (default 0.01)
   *   regions: number (default 1)
   *   columns: number (default 1)
   *   debug: boolean (default false)
   */
  constructor(options?: object | undefined | null)
  /**
   * Register a channel spec. Accepts the same spec shape as JS Brain.
   *
   * spec: { name, emitsReward?, learnActionSequences?, dimensions: [...] }
   * Returns: { channelId: number, dimensionIds: {name: id, ...} }
   */
  registerChannelSpec(spec: object): object
  /**
   * Process a single frame. Accepts Maps matching JS Brain.processFrame.
   *
   * events: Map<channelId, Map<dimId, scalar>> — sensory inputs
   * actions: Map<channelId, Map<dimId, actionValue>> — forced actions (empty = infer)
   * rewards: Map<channelId, reward> — reward for previous frame's actions
   * Returns: { inferences: Map<channelId, [...]>, frame: { elapsed, voteDebug } }
   */
  processFrame(events: object, actions: object, rewards: object): object
  /**
   * Direct supervised learning: wire action connections from context neurons
   * and return inference result to test if learning took effect.
   */
  learn(actions: object, rewards: object): object
  /** Run inference on the current context without advancing the frame. */
  infer(): object
  /** Reset brain memory state for a clean episode start. */
  resetContext(): void
  /** Hard reset: clears ALL learned data. */
  resetBrain(): void
  /** Reset accuracy and reward stats for a new episode. */
  resetAccuracyStats(): void
  /**
   * Set processing mode flags.
   * eventProcessing: when false, freezes context (no aging, no new activations).
   * actionProcessing: when false, suppresses action inference and rewards.
   * learning: when false, skips pattern creation and connection learning (recognition only).
   */
  setProcessingMode(eventProcessing: boolean, actionProcessing: boolean, learning: boolean): void
  /** Look up a dimension ID by its registered name. */
  getDimensionIdByName(name: string): unknown
  /** Look up a neuron ID by its (dimId, bucketId) coordinate. */
  getNeuronIdByCoordinate(dimId: number, bucketId: number): unknown
  /** Save brain state to a labeled backup folder. */
  save(jobDir: string, label: string): void
  /** Load a backup by label. */
  load(jobDir: string, label: string): void
  /** Save brain context (active neurons, frame number, rewards) to a labeled folder. */
  saveContext(jobDir: string, label: string): void
  /** Load brain context from a labeled folder. */
  loadContext(jobDir: string, label: string): void
  /** Get the per-frame summary for the renderer. */
  getFrameSummary(): object
  /** Get episode summary with all diagnostic information. */
  getEpisodeSummary(): object
  /** Get start-of-frame diagnostic snapshot. Returns null when frame was empty. */
  getStartFrameInfo(): unknown
}
